version: "3"
services:
  tdd_vending-machine:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile
      args:
        WORKDIR: /project
    volumes:
      - .:/project
      - ${USERPROFILE-~}/.ssh:/home/vscode/.ssh
    image: tdd_vending-machine-image
    container_name: tdd_vending-machine-container
    tty: true
